# github actionsで使用
services:
  test-backend:
    build:
      context: .
      dockerfile: dockerfile
      target: dev
    image: backend_container:dev
    container_name: test-backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db-container
      - HOST_NAME=test-db
      - PORT_NUMBER=5432
    depends_on:
      - test-db
  test-db:
    image: postgres:16.3
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-container